/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    events: Event;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'zh-Hans') | ('en' | 'zh-Hans')[];
  globals: {
    global: Global;
    'home-page': HomePage;
    'about-page': AboutPage;
    'events-page': EventsPage;
    'volunteer-page': VolunteerPage;
    'give-page': GivePage;
    'support-page': SupportPage;
    'freshman-page': FreshmanPage;
    'plan-your-visit-page': PlanYourVisitPage;
    'thank-you-page': ThankYouPage;
  };
  globalsSelect: {
    global: GlobalSelect<false> | GlobalSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'events-page': EventsPageSelect<false> | EventsPageSelect<true>;
    'volunteer-page': VolunteerPageSelect<false> | VolunteerPageSelect<true>;
    'give-page': GivePageSelect<false> | GivePageSelect<true>;
    'support-page': SupportPageSelect<false> | SupportPageSelect<true>;
    'freshman-page': FreshmanPageSelect<false> | FreshmanPageSelect<true>;
    'plan-your-visit-page': PlanYourVisitPageSelect<false> | PlanYourVisitPageSelect<true>;
    'thank-you-page': ThankYouPageSelect<false> | ThankYouPageSelect<true>;
  };
  locale: 'en' | 'zh-Hans';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  role: 'admin' | 'editor' | 'member';
  /**
   * Toggle to activate/deactivate user account
   */
  isActive?: boolean | null;
  /**
   * Last login time
   */
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Event title
   */
  title: string;
  /**
   * URL-friendly identifier, must be unique
   */
  slug: string;
  /**
   * Event date
   */
  date: string;
  time?: {
    /**
     * Start time (24-hour format)
     */
    start?: string | null;
    /**
     * End time (24-hour format)
     */
    end?: string | null;
  };
  location?: {
    /**
     * Venue name
     */
    venue?: string | null;
    /**
     * Detailed address
     */
    address?: string | null;
  };
  /**
   * Event description
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Event image gallery
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Event video link (YouTube, Vimeo, etc.)
   */
  content_video_url?: string | null;
  registration?: {
    /**
     * Whether registration is required
     */
    required?: boolean | null;
    /**
     * Registration link
     */
    url?: string | null;
    /**
     * Registration deadline
     */
    deadline?: string | null;
  };
  /**
   * Event creator
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  isActive?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  time?:
    | T
    | {
        start?: T;
        end?: T;
      };
  location?:
    | T
    | {
        venue?: T;
        address?: T;
      };
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  content_video_url?: T;
  registration?:
    | T
    | {
        required?: T;
        url?: T;
        deadline?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global".
 */
export interface Global {
  id: number;
  navigation?: {
    /**
     * Site logo
     */
    logo?: (number | null) | Media;
    websiteTitleCN?: string | null;
    websiteTitleEN?: string | null;
    menuItems?:
      | {
          label: string;
          /**
           * Internal path (e.g., /about) or external URL
           */
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    contactInfo?: {
      address?: string | null;
      /**
       * Contact phone number, e.g., +1 (555) 123-4567
       */
      phone?: string | null;
      /**
       * Contact email address, e.g., info@ccm.org
       */
      email?: string | null;
    };
    socialMedia?:
      | {
          platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'youtube';
          url: string;
          id?: string | null;
        }[]
      | null;
    copyrightText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    title?: string | null;
    /**
     * Hero background image
     */
    backgroundImage: number | Media;
    subtitle?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Hero call-to-action button text
     */
    buttonText?: string | null;
    /**
     * Hero call-to-action button URL
     */
    buttonUrl?: string | null;
  };
  intro?: {
    /**
     * First introduction section
     */
    part1?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * YouTube embed URL for introduction video
     */
    videoUrl?: string | null;
    /**
     * Second introduction section (after video)
     */
    part2?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Conclusion section
     */
    conclusion?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  meet?: {
    title?: string | null;
    cards?:
      | {
          title: string;
          /**
           * URL slug (e.g., "about", "events")
           */
          slug: string;
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    title?: string | null;
    /**
     * Hero background image
     */
    backgroundImage: number | Media;
  };
  intro?: {
    subtitle?: string | null;
    title?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  history?: {
    subtitle?: string | null;
    title?: string | null;
    items?:
      | {
          image: number | Media;
          description: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[]
      | null;
  };
  team?: {
    subtitle?: string | null;
    title?: string | null;
    members?:
      | {
          name: string;
          position?: string | null;
          photo: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page".
 */
export interface EventsPage {
  id: number;
  hero: {
    hero_title: string;
    hero_image: number | Media;
  };
  upcomingEvents: {
    upcoming_events_subtitle?: string | null;
    upcoming_events_title: string;
    /**
     * Message to show when no upcoming events
     */
    no_events_message?: string | null;
  };
  pastEvents: {
    past_events_subtitle?: string | null;
    past_events_title: string;
    view_all_text?: string | null;
    /**
     * Message to show when no past events
     */
    past_events_empty_text?: string | null;
  };
  seo?: {
    /**
     * Meta description for events page
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-page".
 */
export interface VolunteerPage {
  id: number;
  hero: {
    hero_title: string;
    hero_image: number | Media;
  };
  introduction: {
    introduction_subtitle?: string | null;
    introduction_title: string;
    introduction_content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  application?: {
    application_button_text?: string | null;
    /**
     * URL to volunteer application form
     */
    application_button_url?: string | null;
  };
  volunteer?: {
    volunteer_title?: string | null;
    volunteer_content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "give-page".
 */
export interface GivePage {
  id: number;
  hero: {
    hero_title: string;
    hero_image: number | Media;
  };
  content: {
    introduction_subtitle?: string | null;
    introduction_title: string;
    introduction_content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    donation_button_text?: string | null;
    /**
     * URL to donation form or payment processor
     */
    donation_button_url?: string | null;
  };
  payment_methods?: {
    zelle_title?: string | null;
    zelle_content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    check_title?: string | null;
    check_content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  resources?: {
    pdf_links?:
      | {
          title: string;
          file: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-page".
 */
export interface SupportPage {
  id: number;
  hero: {
    hero_title: string;
    hero_image: number | Media;
  };
  content?: {
    info_sections?:
      | {
          /**
           * Small subtitle above heading
           */
          title?: string | null;
          /**
           * Main section heading
           */
          subtitle?: string | null;
          content: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "freshman-page".
 */
export interface FreshmanPage {
  id: number;
  hero: {
    hero_title: string;
    hero_subtitle?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    hero_image: number | Media;
  };
  content: {
    introduction_title: string;
    introduction_content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    resources_title?: string | null;
    resources_content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    info_sections?:
      | {
          title: string;
          subtitle?: string | null;
          content: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          image?: (number | null) | Media;
          button_text?: string | null;
          button_url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-your-visit-page".
 */
export interface PlanYourVisitPage {
  id: number;
  hero: {
    hero_title: string;
    hero_image: number | Media;
  };
  introduction: {
    introduction_subtitle?: string | null;
    introduction_title: string;
    introduction_content?:
      | {
          content: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  location?: {
    /**
     * Google Maps embed URL for the iframe src
     */
    location_map_link?: string | null;
    location_description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  hours?: {
    hours_title?: string | null;
    hours_content?:
      | {
          content: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "thank-you-page".
 */
export interface ThankYouPage {
  id: number;
  hero: {
    hero_title: string;
    hero_subtitle?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    hero_image: number | Media;
  };
  content: {
    content_title: string;
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  navigation?: {
    home_button_text?: string | null;
    contact_button_text?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global_select".
 */
export interface GlobalSelect<T extends boolean = true> {
  navigation?:
    | T
    | {
        logo?: T;
        websiteTitleCN?: T;
        websiteTitleEN?: T;
        menuItems?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        contactInfo?:
          | T
          | {
              address?: T;
              phone?: T;
              email?: T;
            };
        socialMedia?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        copyrightText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        backgroundImage?: T;
        subtitle?: T;
        buttonText?: T;
        buttonUrl?: T;
      };
  intro?:
    | T
    | {
        part1?: T;
        videoUrl?: T;
        part2?: T;
        conclusion?: T;
      };
  meet?:
    | T
    | {
        title?: T;
        cards?:
          | T
          | {
              title?: T;
              slug?: T;
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        backgroundImage?: T;
      };
  intro?:
    | T
    | {
        subtitle?: T;
        title?: T;
        content?: T;
      };
  history?:
    | T
    | {
        subtitle?: T;
        title?: T;
        items?:
          | T
          | {
              image?: T;
              description?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        subtitle?: T;
        title?: T;
        members?:
          | T
          | {
              name?: T;
              position?: T;
              photo?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page_select".
 */
export interface EventsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        hero_title?: T;
        hero_image?: T;
      };
  upcomingEvents?:
    | T
    | {
        upcoming_events_subtitle?: T;
        upcoming_events_title?: T;
        no_events_message?: T;
      };
  pastEvents?:
    | T
    | {
        past_events_subtitle?: T;
        past_events_title?: T;
        view_all_text?: T;
        past_events_empty_text?: T;
      };
  seo?:
    | T
    | {
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-page_select".
 */
export interface VolunteerPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        hero_title?: T;
        hero_image?: T;
      };
  introduction?:
    | T
    | {
        introduction_subtitle?: T;
        introduction_title?: T;
        introduction_content?: T;
      };
  application?:
    | T
    | {
        application_button_text?: T;
        application_button_url?: T;
      };
  volunteer?:
    | T
    | {
        volunteer_title?: T;
        volunteer_content?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "give-page_select".
 */
export interface GivePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        hero_title?: T;
        hero_image?: T;
      };
  content?:
    | T
    | {
        introduction_subtitle?: T;
        introduction_title?: T;
        introduction_content?: T;
        donation_button_text?: T;
        donation_button_url?: T;
      };
  payment_methods?:
    | T
    | {
        zelle_title?: T;
        zelle_content?: T;
        check_title?: T;
        check_content?: T;
      };
  resources?:
    | T
    | {
        pdf_links?:
          | T
          | {
              title?: T;
              file?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-page_select".
 */
export interface SupportPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        hero_title?: T;
        hero_image?: T;
      };
  content?:
    | T
    | {
        info_sections?:
          | T
          | {
              title?: T;
              subtitle?: T;
              content?: T;
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "freshman-page_select".
 */
export interface FreshmanPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        hero_title?: T;
        hero_subtitle?: T;
        hero_image?: T;
      };
  content?:
    | T
    | {
        introduction_title?: T;
        introduction_content?: T;
        resources_title?: T;
        resources_content?: T;
        info_sections?:
          | T
          | {
              title?: T;
              subtitle?: T;
              content?: T;
              image?: T;
              button_text?: T;
              button_url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-your-visit-page_select".
 */
export interface PlanYourVisitPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        hero_title?: T;
        hero_image?: T;
      };
  introduction?:
    | T
    | {
        introduction_subtitle?: T;
        introduction_title?: T;
        introduction_content?:
          | T
          | {
              content?: T;
              image?: T;
              id?: T;
            };
      };
  location?:
    | T
    | {
        location_map_link?: T;
        location_description?: T;
      };
  hours?:
    | T
    | {
        hours_title?: T;
        hours_content?:
          | T
          | {
              content?: T;
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "thank-you-page_select".
 */
export interface ThankYouPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        hero_title?: T;
        hero_subtitle?: T;
        hero_image?: T;
      };
  content?:
    | T
    | {
        content_title?: T;
        content?: T;
      };
  navigation?:
    | T
    | {
        home_button_text?: T;
        contact_button_text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}